select * from CUSTOMER,INVOICE,INVOICE_ITEM; 
select LastName,FirstName,Phone from Customer;
select LastName,FirstName,Phone from Customer where FirstName = 'Nikki'; 
select LastName,FirstName,Phone,DateIn,DateOut from customer,invoice where TotalAmount > 100.00;
select LastName, FirstName, Phone from Customer where FirstName like 'B%';
select lastName, FirstName, Phone from Customer where LastName like '%cat%';
select LastName, FirstName, Phone from Customer where SUBSTR(Phone, 2, 2) = '23'; 
select MAX(TotalAmount) AS MaximumTotalAmount, MIN(TotalAmount) AS MinimumTotalAmount from Invoice;
select AVG(TotalAmount) AS AverageTotalAmount from Invoice;
select COUNT(*) AS NumberOfCustomers from Customer;
select LastName, FirstName from Customer group by LastName, FirstName;
select LastName, FirstName, COUNT(*) AS NumberOfCustomersWithThisName from Customer group by LastName, FirstName;